In [1]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

# Requests sends and recieves HTTP requests.
import requests


import json
import time
import copy

In [2]:
#pull census variables 
#storing census variable names(unreadable) with readable column names 
var_req = requests.get('https://api.census.gov/data/2018/acs/acs1/spp/variables.json').json()


col_name = {}
variables = var_req['variables']

for k, v in variables.items():
    col_name[k] = v['label']
    
#still need to clean up the column names and remove !! and other unnecssary data.

In [3]:
#remove all the columns that have PR in them
clean_col_name = col_name.copy()
stat = 'PR'


for k, v in col_name.items():
    if stat in k:
        del clean_col_name[k]

In [4]:
#flexible pull request for api call, generates names for api url
def census_name_pull(name_dict, word_search):
    name_list = ['NAME','GEO_ID']


    for k, v in name_dict.items():
        if word_search in v:
            name_list.append(k)
    return sorted(name_list)

In [5]:
#pull columns for sex & age by county in state
sex_age_pull = census_name_pull(clean_col_name,'SEX AND AGE')
sex_age_pull

['GEO_ID',
 'NAME',
 'S0201_006E',
 'S0201_007E',
 'S0201_008E',
 'S0201_009E',
 'S0201_010E',
 'S0201_011E',
 'S0201_012E',
 'S0201_013E',
 'S0201_014E',
 'S0201_015E',
 'S0201_016E',
 'S0201_017E',
 'S0201_018E',
 'S0201_019E',
 'S0201_020E',
 'S0201_021E',
 'S0201_022E',
 'S0201_023E',
 'S0201_024E',
 'S0201_025E',
 'S0201_026E',
 'S0201_027E',
 'S0201_028E',
 'S0201_029E',
 'S0201_030E',
 'S0201_031E',
 'S0201_032E',
 'S0201_033E',
 'S0201_034E',
 'S0201_035E',
 'S0201_036E',
 'S0201_037E']

In [6]:
#pull columns for employment status by county in state
emp_stat_pull = census_name_pull(clean_col_name,'EMPLOYMENT STATUS')

In [7]:
#pull columns for industry by county in state
industry_pull = census_name_pull(clean_col_name,'INDUSTRY')

In [8]:
#pull columns for income by county in state
income_pull = census_name_pull(clean_col_name,'INCOME')

In [9]:
industry_pull

['GEO_ID',
 'NAME',
 'S0201_194E',
 'S0201_195E',
 'S0201_196E',
 'S0201_197E',
 'S0201_198E',
 'S0201_199E',
 'S0201_200E',
 'S0201_201E',
 'S0201_202E',
 'S0201_203E',
 'S0201_204E',
 'S0201_205E',
 'S0201_206E',
 'S0201_207E']

In [10]:
#connect to api_url for census per 
# get_vars = [sex_age_pull, emp_stat_pull, industry_pull, income_pull]

def api_pull_request(get_vars):

    api_key = 'ce30285f0f2fedc096b5bf054c7d573ea6558309'
    base_url = 'https://api.census.gov/data/2018/acs/acs1/spp?'

    predicates = {}
    predicates['get'] = ','.join(get_vars)
    predicates['for'] = 'county:*'
    predicates['in'] = 'state:*'
    predicates['key'] = api_key
    
    r = requests.get(base_url, params=predicates)
    
    return r.json()

# api_url = '''https://api.census.gov/data/2018/acs/acs1/spp?get=NAME,GEO_ID,S0201_001E,S0201_006E,S0201_213E,S0201_194E&for=county:*&in=state:*&key=ce30285f0f2fedc096b5bf054c7d573ea6558309'''

In [11]:
#created sex and age pull request and dataframe
sex_age_data = api_pull_request(sex_age_pull)
sex_age_df = pd.DataFrame(sex_age_data)

In [12]:
#created employee status pull request and dataframe
emp_stat_data = api_pull_request(emp_stat_pull)
emp_stat_df = pd.DataFrame(emp_stat_data)

In [13]:
#created income pull request and dataframe
income_data = api_pull_request(income_pull)
income_df = pd.DataFrame(income_data)

In [14]:
#created industry pull request and dataframe
industry_data = api_pull_request(industry_pull)
industry_df = pd.DataFrame(industry_data)

In [27]:
#save all dataframes
sex_age_df.to_csv('../data/sex_age_df.csv')
emp_stat_df.to_csv('../data/emp_stat_df.csv')
income_df.to_csv('../data/income_df.csv')
industry_df.to_csv('../data/industry_df.csv')

## attempting different view from data profiles tables (DP03)

In [16]:
#pull census variables from acs1 DP02 or DP03
#storing census variable names(unreadable) with readable column names 
detailed_var_req = requests.get('https://api.census.gov/data/2018/acs/acs1/profile/variables.json').json()


detailed_col_name = {}
detailed_variables = detailed_var_req['variables']

for k, v in detailed_variables.items():
    detailed_col_name[k] = v['label']
    
#still need to clean up the column names and remove !! and other unnecssary data.

In [17]:
#remove all the columns that have PR in them
clean_detailed_col_name = detailed_col_name.copy()
stat = 'PR'


for k, v in detailed_col_name.items():
    if stat in k:
        del clean_detailed_col_name[k]

In [18]:
#removing percent estimate
clean2 = clean_detailed_col_name.copy()
stat = 'PE'


for k, v in clean_detailed_col_name.items():
    if stat in k:
        del clean2[k]

In [19]:
#flexible pull request for api call, generates names for api url
def census_name_pull(name_dict, word_search):
    name_list = ['NAME','GEO_ID']


    for k, v in name_dict.items():
        if word_search in v:
            name_list.append(k)
    return name_list

In [20]:
detailed_income = census_name_pull(clean2,'INCOME AND BENEFITS')

In [21]:
#api only allows for 50 variables to be called per request
detailed_income50 = detailed_income[:50]

In [22]:
def api_pull_request2(get_vars):

    api_key = 'ce30285f0f2fedc096b5bf054c7d573ea6558309'
    base_url = 'https://api.census.gov/data/2018/acs/acs1/profile?'

    predicates = {}
    predicates['get'] = ','.join(get_vars)
    predicates['for'] = 'place:*'
    predicates['in'] = 'state:*'
    predicates['key'] = api_key
    
    r = requests.get(base_url, params=predicates)
    
    return r.json()

In [23]:
dp02_data_request = api_pull_request2(detailed_income50)
detailed_data_df = pd.DataFrame(dp02_data_request)
detailed_data_df.to_csv('../data/dp02_income_data.csv')

In [24]:
dp02_emp_stat_get = census_name_pull(clean2, 'EMPLOYMENT STATUS')

In [25]:

dp02_emp_stat_data_request = api_pull_request2(dp02_emp_stat_get)
dp02_emp_stat_df = pd.DataFrame(dp02_emp_stat_data_request)
dp02_emp_stat_df.to_csv('../data/dp02_emp_stat_data.csv')

In [26]:
dp02_emp_stat_df

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,NAME,GEO_ID,DP03_0002E,DP03_0003E,DP03_0001E,DP03_0008E,DP03_0009E,DP03_0006E,DP03_0007E,DP03_0004E,...,DP03_0014E,DP03_0015E,DP03_0012E,DP03_0013E,DP03_0010E,DP03_0011E,DP03_0016E,DP03_0017E,state,place
1,"Flagstaff city, Arizona",1600000US0423620,41541,41541,63114,41541,-888888888.0,0,21573,38936,...,3820,2219,20662,18894,31848,20662,8189,6407,04,23620
2,"Gilbert town, Arizona",1600000US0427400,128105,127993,181453,127993,-888888888.0,112,53348,123441,...,20893,11870,60663,58041,94266,60663,53236,36408,04,27400
3,"San Tan Valley CDP, Arizona",1600000US0464210,47745,47745,75800,47745,-888888888.0,0,28055,45260,...,9723,4922,22065,20922,38874,22065,21892,15151,04,64210
4,"Fort Smith city, Arkansas",1600000US0524550,42114,42088,68890,42088,-888888888.0,26,26776,40665,...,6863,5321,20677,19934,36138,20677,13506,7906,05,24550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
626,"The Woodlands CDP, Texas",1600000US4872656,51369,51267,81688,51267,-888888888.0,102,30319,49140,...,5909,2795,-999999999,-999999999,-999999999,-999999999,22296,13172,48,72656
627,"Chesapeake city, Virginia",1600000US5116000,125191,117970,189761,117970,-888888888.0,7221,64570,113366,...,17736,11059,57627,55703,97830,58523,37747,27412,51,16000
628,"Roanoke city, Virginia",1600000US5168000,50796,50617,79177,50617,-888888888.0,179,28381,46948,...,9112,5579,24767,22859,42888,24884,12568,9228,51,68000
629,"Everett city, Washington",1600000US5322640,64453,62426,90910,62426,-888888888.0,2027,26457,60030,...,8359,6478,28310,27490,43567,28600,12976,10164,53,22640
630,"Madison city, Wisconsin",1600000US5548000,156563,156232,219132,156232,-888888888.0,331,62569,153217,...,15728,11686,76886,75447,111537,77011,26046,20203,55,48000